### ISSUE TITLE
Officially declare the 1.3 version EOL

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#105]
... and deprecate support & maintance for it.

- [ ] Add EOL warning on top of https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/blob/2.x/README.md
- [x] Add EOL warning under https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/tree/master#cakephp-13x

Just to make it clear.

**Comment by xhs345** [comment]
Thanks, didn't know you could use checkboxes like that. Pretty cool. 

Warnings have been added in case any poor soul who's still working with 1.3 comes across them!
