### ISSUE TITLE
Self HABTM issue: Undefined property

### ISSUE THREAD

**Issue by Pablushka** [robwilkerson/CakePHP-Audit-Log-Plugin#108]
Hi, 

Thank you for this plugin. It's really useful. I started using it in my project (cake 2.8) but a little problem with a self HABTM relation:

```
class Empresa extends AppModel {
	public $actsAs = array('AuditLog.Auditable'=> array(
            'habtm' => array('Relacionada')
           )
	);
...
...
...
	public $hasAndBelongsToMany = array(
		'Relacionada' => array(	  
			'className' => 'Empresa',
			'joinTable' => 'empresas_relacionadas',
			'foreignKey' => 'empresa_id',
			'associationForeignKey' => 'relacionada_id',
			'conditions' => '',
			'unique' => true,
		)		
	);
...
...
...
```

Then the following errors are triggered:

- Undefined property: Empresa::$Relacionada [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]
- Trying to get property of non-object [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]

The plugin works very well on the other models.

**Comment by ravage84** [comment]
Can you say, which version you use of the plugin? Have you tried to use the dev-master of the plugin instead? Have you tried to use CakePHP 2.9.x already?

**Comment by Pablushka** [comment]
Hi ravage84,  I follow your suggestion, upgrade to cake 2.9.2 and delete the AuditLog folder and install it again from composer ( it create a git submodule for the plugin). I don't know where the plugin version is, but the last commit id for the master branch is 2ef5687 from october 12 and I can see is the lastest one.

The upgrade and instalation results are ok:

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing cakephp/cakephp (2.8.9)
  - Installing cakephp/cakephp (2.9.2)
    Downloading: 100%

composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing robwilkerson/cakephp-audit-log-plugin (dev-master 2ef5687)
    Cloning 2ef5687f993edb2e06f097353168525a6187af19
```
Unfortunally, the problem with my self-HABTM model persists:

- Notice (8): Undefined property: Empresa::$Relacionada [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]
- Notice (8): Trying to get property of non-object [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]
- Notice (8): Undefined property: Empresa::$Relacionada [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]
- Notice (8): Trying to get property of non-object [APP/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php, line 83]

And these errors occurs in every page in my application (views) breaking all json output too.

**Comment by Pablushka** [comment]
Ok, I fix it. Just trying things like madagascar penguins on the keyboard, I change this:

```
class Empresa extends AppModel {
	public $actsAs = array('AuditLog.Auditable'=> array(
            'habtm' => array('Relacionada')
           )
	);
```

to this:

```
class Empresa extends AppModel {
	public $actsAs = array('AuditLog.Auditable'=> array(
            'habtm' => array('Empresa')
           )
	);
```

And works again. I learned 'habtm' property is an array of model names instead relation names.

Thank you for your help, I really appreciate it so much.

**Comment by ravage84** [comment]
Glad to hear.
Do you think we can and should improve our documentation?

**Comment by Pablushka** [comment]
Honestly, in the documentation you always talk about models, never relation mames, so it is my bad. I apologize for the loss of time so much.

**Comment by ravage84** [comment]
No problem. Thank you for your Feedback.

**Comment by xhs345** [comment]
Glad to see this got resolved!

Closing the issue.
