### ISSUE TITLE
Call to member function create() on null

### ISSUE THREAD

**Issue by jlpuder** [robwilkerson/CakePHP-Audit-Log-Plugin#113]
I just attempted to install this plugin to my app running CakePHP 2.7, and get a fatal error whenever I try to save a model:

**Error:** Call to a member function create() on null	
**File:** /var/www/html/cakephp.git/app/Plugin/AuditLog/Model/Behavior/AuditableBehavior.php	
**Line:** 242

I tried it on several different models, both with and without HABTM relationships and get the same result.

**Comment by xhs345** [comment]
Could you post some code examples? Like what the model looks like and the data you're trying to save

**Comment by jlpuder** [comment]
Model
```
class InventoryItem extends AppModel {

/**
 * Display field
 *
 * @var string
 */
	public $displayField = 'name';
	
	public $actsAs = array('Containable', 'AuditLog.Auditable');

/**
 * Validation rules
 *
 * @var array
 */
	public $validate = array(
		'name' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
				'message' => 'Please enter a name to identify this item.',
				'allowEmpty' => false,
			),
		),
		'status' => array(
			'notBlank' => array(
				'rule' => array('notBlank'),
				'message' => 'Please select an item status.',
			),
		),
	);


	public function afterFind($results, $primary = false) {
		return $results; 
	}

/**
 * belongsTo associations
 *
 * @var array
 */
	public $belongsTo = array(
		'User' => array(
			'className' => 'User',
			'foreignKey' => 'user_id',
		),
		'Department' => array(
			'className' => 'Department',
			'foreignKey' => 'department_id'
		)
	);
}
```
The data contained within the model is as follows:

- id: PK auto increment
- department_id : FK integer
- name: text
- serial: text
- item_condition: text
- status: text
-user_id: NULL or int
- modified: datetime
- notes: text

**Comment by xhs345** [comment]
Can you try to comment out the afterFind method (or set useConsistentAfterFind to false on the model, see: https://book.cakephp.org/2.0/en/appendices/2-6-migration-guide.html#id1) and see if that changes anything ?

**Comment by jlpuder** [comment]
No changes with either method.

I tried to get some more information from the logs by adding some checks around the error (Line 242) and this is what I found, not sure if it gets us anywhere:

- `$this->log($Model->hasMany)` shows that `AuditLog.Audit` is attached with className `AuditLog.Audit`
- `is_null($Model)` is false
- `is_null($Model->Audit)` is true (?)

**Comment by ravage84** [comment]
Can you debug it with a debugger like [XDebug](https://xdebug.org/) to see what is happening?

**Comment by jlpuder** [comment]
```
TRACE START [2017-01-21 22:46:45]
    0.0568    8123064                             -> Model->__get('Audit') /var/www/html/cakephp.git/lib/Cake/Utility/ObjectCollection.php:243
    0.0568    8123064                               -> Model->__isset('Audit') /var/www/html/cakephp.git/lib/Cake/Utility/ObjectCollection.php:919
    0.0568    8123112                                >=> FALSE
    0.0568    8123112                              >=> NULL
    0.0586    8172760                             -> App::shutdown() /var/www/html/cakephp.git/lib/Cake/Core/App.php:0


```
Here's the trace around the line that keeps erroring - Audit model coming up null, which I guess we knew already. Further up, `Model->bindModel` is showing a return of `TRUE`, indicating successful association, however the `Model->__isset('Audit')` returns `FALSE`, indicating the association is not loaded or cannot be created, right?

**Comment by jlpuder** [comment]
I must have had something wrong with my Cake installation, I moved everything into a fresh install v2.9 and all is working. Thanks for the help anyways!

**Comment by xhs345** [comment]
Was just about to try it out, glad you could figure it out :)

**Comment by ravage84** [comment]
I guess this behavior hints at a backwards incompatibility.
@jlpuder it would be helpful to know if it works in a fresh 2.7, 28 install, too.

**Comment by jlpuder** [comment]
I used the last minor version of each release and it seems like something changed between 2.7.10 and 2.8.9. 2.7 didn't work (same error) and 2.8 did.
