### ISSUE TITLE
Audits not created for updated records that didn't have data set originally

### ISSUE THREAD

**Issue by Osydius** [robwilkerson/CakePHP-Audit-Log-Plugin#119]
An audit isn't created when updating records that had data set as NULL or false. For example:

Original data:
```
'Blog' => [
    'id' => 1,
    'title' => 'Foo bar',
    'text' => NULL,
]
```

New data:
```
'Blog' => [
    'id' => 1,
    'title' => 'Foo bar',
    'text' => 'bar foo foo bar',
]
```

An EDIT audit will not be created for the change in the `text` field as it wasn't set originally. I believe the issue is with using `Hash::check()` to see if the $property is set in the afterSave method of the behavior as this is returning false even though the property exists in the data.

**Comment by xhs345** [comment]
Thanks for reporting the issue. I will look into it as well.. but if you can create a Pull Request to fix the issue then it would be highly appriciated

**Comment by xhs345** [comment]
Issue should be fixed with changes from @pedropuppim
