### ISSUE TITLE
Plugin should handle models configured for soft delete

### ISSUE THREAD

**Issue by robwilkerson** [robwilkerson/CakePHP-Audit-Log-Plugin#17]
In many cases a soft delete is preferred. The plugin should be able to recognize that situation and treat those as delete actions. This was suggested by Christopher Vrooman in [this comment](https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/pull/16#issuecomment-11437426) on a pull request.

**Comment by xhs345** [comment]
Clearing up old issues. CakeDC Utils.SoftDelete is now supported. See #45
