### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by CaioLorensetti** [robwilkerson/CakePHP-Audit-Log-Plugin#21]
Hi.
Thanks for the behaviour.
I had this problem:
Unsupported operand types in <path>/lib/Cake/Core/CakePlugin.php on line 78

You can help?

**Comment by KhinChoChoTun** [comment]
Hi, 
I had this problem:
Unsupported operand types in /lib/Cake/Core/CakePlugin.php on line 127
You can help?
