### ISSUE TITLE
Don't bind model on each callback

### ISSUE THREAD

**Issue by angelxmoreno** [robwilkerson/CakePHP-Audit-Log-Plugin#29]
I understand why you bind the `Audit` and `AuditDelta` models, but I do not understand the goal in binding `Audit` to the model that is being audited.

**Comment by ravage84** [comment]
@angelxmoreno I started implementing that in #102

**Comment by ravage84** [comment]
@xhs345  closable due to the merge of #102 .

**Comment by xhs345** [comment]
Ok
