### ISSUE TITLE
Purpose behind 'json_object' => json_encode( $audit ) ?

### ISSUE THREAD

**Issue by angelxmoreno** [robwilkerson/CakePHP-Audit-Log-Plugin#30]
My rows are too big, even for longText on MySQL. I am curious what the goal was here especially since the deltas are already tracking what changed.

**Comment by ravage84** [comment]
@xhs345 let's close this and concentrate on #78. This issue is mentioned there, so it's referenced.

**Comment by xhs345** [comment]
Agree
