### ISSUE TITLE
Get related models within same audit

### ISSUE THREAD

**Issue by LDSign** [robwilkerson/CakePHP-Audit-Log-Plugin#32]
Hi

I am using this nice plugin on several models, one of them (users) is related to some others via hasOne (e.g. profiles). Each related model has the plugin attached and everything works nicely together. On saving associated data through the main model AuditLog creates logs for each model like expected.

So, I would like to build an interface to revert back to a previous state on a given time through the main model (users). But unfortunatley each "related" entry in the audits-table exists on its own (profiles).

Of course I could knock everthing together manually, but there must be an easy way to get an audit with all related data. Has anyone done this before? Any suggestions?

Thanks,
Frank

**Comment by ravage84** [comment]
@xhs345  :-1: , closing?

**Comment by xhs345** [comment]
Since no one else has been interested it's probably a good time, yes
