### ISSUE TITLE
ERROR in AuditableBehavior.php while deleting Objects

### ISSUE THREAD

**Issue by Drugsteroid** [robwilkerson/CakePHP-Audit-Log-Plugin#36]
Hello,

you have got a mistake in your code.
If you have no 'json_object' in your model->alias:

In the function "afterDelete(Model $model)" there is this statement:
                if (($this->_settings[$model->alias]['json_object']) {
			$data['Audit']['json_object'] = json_encode($audit);
		}
BUT it should be this:
                if (!empty($this->_settings[$model->alias]['json_object'])) {
			$data['Audit']['json_object'] = json_encode($audit);
		}

Please change your code accordingly, it will always give you an error while deleting if this json-Object is not defined.

**Comment by ravage84** [comment]
This section of the code does not seem to exist anymore. I guess it can be closed.

**Comment by xhs345** [comment]
Yes, that's true. Closing this issue
