### ISSUE TITLE
Packagist error when trying to publish

### ISSUE THREAD

**Issue by inigoflores** [robwilkerson/CakePHP-Audit-Log-Plugin#46]
Oh dear!

> The package name robwilkerson/CakePHP-Audit-Log-Plugin is invalid, it should not contain uppercase characters. We suggest using robwilkerson/cake-php-audit-log-plugin instead.

Can the repository be renamed?

**Comment by robwilkerson** [comment]
Oh, noz. Well, probably, but the first thing I'd try to do is rename the Composer package itself. Just make that lowercase and see whether things work ok...

**Comment by inigoflores** [comment]
That did the trick. Let me create the pull request.

**Comment by inigoflores** [comment]
Ok. Published, but run on to another problem.

>
GitHub Service Hook

>Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Webhooks & Services". Add a "Packagist" service, and configure it with your API token, plus your Packagist username. Check the "Active" box and submit the form. You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated.

I've been provided with an API token which I believe should be kept private, but I can email you if you wish. Alternatively, perhaps it makes more sense that you deal with Packagist directly (it's surprisingly easy).

**Comment by robwilkerson** [comment]
Oy. They surely don't make this easy. I created an account, got a token and think things are configured properly. Please let me know if you see otherwise, either now or in the future.

**Comment by inigoflores** [comment]
It worked as expected! It didn't even complain about the upper case in the package name (as per the instructions).

Thanks!
