### ISSUE TITLE
Issue CakePHP 3.0 -Audit-Log-Plugin

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [robwilkerson/CakePHP-Audit-Log-Plugin#52]
Hi,
Below is the Audit log plugin behavior with cakephp 3.0 version.In that i am not able to insert the 'created' field in 'audits' table.
please resolve the issue and if need please the improve the code quality.

<?php
namespace AuditLog\Model\Behavior;

use ArrayObject;
use Cake\ORM\Behavior;
use Cake\Event\Event;
use Cake\Datasource\EntityInterface;
use Cake\ORM\Query;
use Cake\ORM\Table;
use Cake\Utility\Text;
use Cake\ORM\TableRegistry;

/**
 * Records changes made to an object during save operations.
 */
class AuditableBehavior extends Behavior
{
    /**
     * A copy of the object as it existed prior to the save. We're going
     * to store this off so we can calculate the deltas after save.
     *
     * @var \Cake\ORM\Table
     */
    protected $_original;

    /**
     * Table instance
     *
     * @var \Cake\ORM\Table
     */
    protected $_table;
    protected $_ignore_properties = array();
    
    /**
     * The request_id, a unique ID generated once per request to allow multiple record changes to be grouped by request
     *  
     */
    private static $_request_id = null;
    private function request_id() {
      if (empty(self::$_request_id)) {
          self::$_request_id = Text::uuid();
      }
      return self::$_request_id;
    }

    public function __construct(Table $table, array $config){
        parent::__construct($table, $config);
        $this->_table = $table;
        $this->_ignore_properties = $config;
    }
    
    /**
     * @param Event $event
     * @param EntityInterface $entity
     */
    public function afterSave(Event $event, EntityInterface $entity, ArrayObject $options)
    {
        //before change the data 
        $arrOldData = $entity->extractOriginal($entity->visibleProperties());
        //updated fields array object
        $arrUpdatedProperties = $entity->extractOriginalChanged($entity->visibleProperties());
        //updated data object
        $arrUpdatedData = $entity->jsonSerialize();
        //audit data
        $arrData = array(
            'id'=>self::request_id(),
            'event'      => ($entity->isNew()) ? 'CREATE' : 'EDIT',
            'model'      => $event->subject()->alias(),
            'entity_id'  => $entity->id,
            'request_id' => self::request_id(),
            'json_object'=> json_encode( $arrUpdatedData ),
            'source_id'  => isset( $source['id'] ) ? $source['id'] : null,
            'description'=> isset( $source['description'] ) ? $source['description'] : null
        );
        //saving audit record
        $auditTable = TableRegistry::get('Audits');
        $audit = $auditTable->newEntity($arrData);
        $auditTable->save($audit);
        
        $auditDeltaTable = TableRegistry::get('AuditDeltas');
        foreach($arrUpdatedProperties as $sPropertyName=>$sValue)
        {
            //ignore the fields
            if(in_array($sPropertyName, $this->_ignore_properties)){
                continue;
            }
            $delta = array(
                    'id'=>  Text::uuid(),
                    'audit_id' => $audit->id,
                    'property_name' => $sPropertyName,
                    'old_value'     => $sValue,
                    'new_value'     => $entity->$sPropertyName
            );
            $auditDeltas = $auditDeltaTable->newEntity($delta);
            $auditDeltaTable->save($auditDeltas);
        }
    }

    /**
     * @param Event $event
     * @param EntityInterface $entity
     * @param ArrayObject $options
     */
    public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)
    {
        return true;
    }
}

**Comment by robwilkerson** [comment]
The `master` branch for Cake 3.x is a complete rewrite and very much a work in progress. Keep an eye on the dev-3.x branch to watch the progress. @xhs345, please jump in if I've misrepresented the current state of things.

**Comment by ravikanthhtnakivar** [comment]
The above Behavior is working fine for me...but having the problem is 'created' timestamp is not inserting in 'audits' table.

**Comment by xhs345** [comment]
Hi @ravikanthhtnakivar and thanks a lot for your contribution! I have two question for your code before I can test it:
1. Where are the implementations for the methods extractOriginal and extractOriginalChanged? The way it is written in the code they should be part of the EntityInterface, but they aren't by default.

2. What is the variable $arrOldData used for? It's not used after being declared.

Thanks!

**Comment by ravikanthhtnakivar** [comment]
Hi ,
Thanks for reply @xhs345,
1)extractOriginal and extractOriginalChanged are cakephp 3.0 predefined methods.
2)$entity->id is valid,already checked.
3)$arrOldData is the form old data before changed the properties.
 The above code is working fine except the above issues.
please fix the above issues if need simplify the code quality.
thanks

**Comment by xhs345** [comment]
Ah, found the methods in Cake\Datasource\EntityTrait. I'll try to look more into it in the next days

**Comment by ravikanthhtnakivar** [comment]
thanks @xhs345

**Comment by ravikanthhtnakivar** [comment]
Hi xhs345,
Any updates on the above please?

**Comment by xhs345** [comment]
I still had some issues with it I couldn't figure out yet (wasn't writing anything to the database). 
But because we didn't have any code before, you say it's working for you and also to make it easier for others to look at the code I merged it with the current codebase. 
If you have more updates just create a pull request. I'll get back to it once I found the problem

**Comment by xhs345** [comment]
Closing this for now. If there is serious interested in pushing a 3.x version for this a new issue can be opened
