### ISSUE TITLE
New release overdue

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#64]
People shouldn't use a dev-master revision as a dependency in their apps.
The last release [1.0.1](https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/releases/tag/1.0.1) was tagged on 4 Sep 2011 .

Could you please tag a new release?
Either 1.1.0 or 1.0.2,  depending on how much was added/changed.

See [SemVer](http://semver.org/) for further guidance on the release numbers.

**Comment by ravage84** [comment]
I recommend to create two releases:
Before my several changes and
after (probably a minor version jump in between).

**Comment by xhs345** [comment]
Thank you you for all the contributions! I must admit that it"s quite a bit to tackle, but I'll try to get some things done in the next couple of days. 

Are you still interested in working as a collaborator on this plugin? If so then would vote to add you @robwilkerson

**Comment by ravage84** [comment]
No problem, you're welcome.
And thank you guys for the good work up to now.
Makes my life much easier, as I don't need to write the whole code :smirk_cat: .

The decision, whether this plugin gets used in one of my projects will be made next week.
Depending on this, I would agree to help maintain it.

**Comment by ravage84** [comment]
If it helps you, you can write me by e-mail or Skype (same as e-mail).

**Comment by xhs345** [comment]
Thanks, will do that if a problem arises!

New release with version 2.0 (the old release was from 2011 and for Cake 1.x)
