### ISSUE TITLE
Use plugin syntax for model names

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#79]
Consider integrating the following change:
https://github.com/tranfuga25s/CakePHP-Audit-Log-Plugin/commit/b2ae488d49f66b0977da3b23ca649a51fccc23ca

**Comment by ravage84** [comment]
@steampilot in the mood of taking care of this?

**Comment by xhs345** [comment]
Merge fixes issue
