### ISSUE TITLE
Document the event callbacks

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#82]
The event callbacks such as:
- afterAuditCreate
- afterAuditUpdate
- afterAuditProperty

are currently not documented.

**Comment by ravage84** [comment]
It seems the event callback

- afterAuditDelete

does not exist.

**Comment by ravage84** [comment]
The ``afterAuditDelete`` hook was mentioned [here](https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/pull/16#issuecomment-11441790) .

**Comment by ravage84** [comment]
They seem to date back to 2010 https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/commit/59ca094df5f6af2d9439d9e7a722a5a3614b6457#diff-a5728d8bda7296e6cd5a6907a113b619R182

**Comment by xhs345** [comment]
A simple documentation has been added for the three callbacks.

You think this is ok or do you have any other ideas?

**Comment by xhs345** [comment]
Closing this since basic documentation has been added
