### ISSUE TITLE
Make description field more flexible

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#84]
The description field seems to be filled by the ``currentUser()`` method:

https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/blob/c69e83c2929d2f4896f34e9d12743f0e701de07f/Model/Behavior/AuditableBehavior.php#L165

This functionality is not dcumented anywhere and I doubt most people have a column ``description`` in their ``users`` table, thus this field stays empty in the ``audits`` table all the time.

It should be configurable, falling back to the current field name ``description`` for backwards compatibilty.

**Comment by xhs345** [comment]
I updated the documentation and added a note about the field.

I agree that having something more configurable would be good

**Comment by ravage84** [comment]
I guess the documentation fix does suffice. :bow:
