### ISSUE TITLE
Undefined index notice on nested call

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#97]
My situation:

`Rack` hasMany `RackUnit` (fully pedendent)
`RackUnit` belongsTo `Reservation` (optionally)

Deleting a `Rack`, deletes all its `RackUnit`.
If one of those `RackUnit` belongTo a `Reservation`, that `Reservation` will be deleted, too.
If a `Reservation` gets deleted, another behavior will unset (means updated, not deleted) all reserved `RackUnit`.

This leads to a nested call stack, which in turn leads to a `Undefined index: RackUnit` notice.

The simplified call stack is:
1. beforeDelete() RackUnit 123
   - Sets the original data for RackUnit 123
2. delete() Reservation ABC
3. Update RackUnit 123
4. beforeSave() RackUnit 123
   - Overwrites the original data for RackUnit 123 (still same content)
5. afterSave() RackUnit 123
   - Unsets the original data for RackUnit 123
6. afterDelete()  RackUnit 123
   - Original data for RackUnit 123 is missing!

I see two workarounds an one solution.
1. Workaround 1: Do not unset the original data, which means the original data stacks up. Is this a problem?
2. Workaround 2: Return empty arrray, if key is not set, which is a silent error
3. Solution: Implement a pushable/popable stack of original data.

**Comment by ravage84** [comment]
Both workarounds seem to work and pass the (updated) tests.

**Comment by ravage84** [comment]
Not unsetting the original data could be a problem on this line:
https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/blob/2.0.1/Model/Behavior/AuditableBehavior.php#L210

@xhs345  do you know why there is no ``afterAuditDelete`` callback hook?

**Comment by xhs345** [comment]
@ravage84 Nope, don't know why

**Comment by ravage84** [comment]
Easy, already documented as #82

**Comment by xhs345** [comment]
Closing this since your fix has been merged
